apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-app
  namespace: argocd
spec:
  project: default
  source:
  repoURL: https://github.com/pranathi-nallamilli/argocd.git
    targetRevision: HEAD
    path: K8s/app1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: first-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
